/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppEnquiriesRouteImport } from './routes/_app/enquiries'
import { Route as AppExamsRouteImport } from './routes/_app/exams'
import { Route as AppFeesRouteImport } from './routes/_app/fees'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppGuideRouteImport } from './routes/_app/guide'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppPapersRouteImport } from './routes/_app/papers'
import { Route as AppPrintRouteImport } from './routes/_app/print'
import { Route as AppRoutineRouteImport } from './routes/_app/routine'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppTeachersRouteImport } from './routes/_app/teachers'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students.index'
import { Route as AppStudentsIdRouteImport } from './routes/_app/students.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppEnquiriesRoute = AppEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppPapersRoute = AppPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintRoute = AppPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutineRoute = AppRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/enquiries': typeof AppEnquiriesRoute
  '/exams': typeof AppExamsRoute
  '/fees': typeof AppFeesRoute
  '/finance': typeof AppFinanceRoute
  '/guide': typeof AppGuideRoute
  '/more': typeof AppMoreRoute
  '/papers': typeof AppPapersRoute
  '/print': typeof AppPrintRoute
  '/routine': typeof AppRoutineRoute
  '/settings': typeof AppSettingsRoute
  '/setup': typeof AppSetupRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/teachers': typeof AppTeachersRoute
  '/students/$id': typeof AppStudentsIdRoute
  '/students/': typeof AppStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/attendance': typeof AppAttendanceRoute
  '/enquiries': typeof AppEnquiriesRoute
  '/exams': typeof AppExamsRoute
  '/fees': typeof AppFeesRoute
  '/finance': typeof AppFinanceRoute
  '/guide': typeof AppGuideRoute
  '/more': typeof AppMoreRoute
  '/papers': typeof AppPapersRoute
  '/print': typeof AppPrintRoute
  '/routine': typeof AppRoutineRoute
  '/settings': typeof AppSettingsRoute
  '/setup': typeof AppSetupRoute
  '/teachers': typeof AppTeachersRoute
  '/': typeof AppIndexRoute
  '/students/$id': typeof AppStudentsIdRoute
  '/students': typeof AppStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/enquiries': typeof AppEnquiriesRoute
  '/_app/exams': typeof AppExamsRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/guide': typeof AppGuideRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/papers': typeof AppPapersRoute
  '/_app/print': typeof AppPrintRoute
  '/_app/routine': typeof AppRoutineRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/students/$id': typeof AppStudentsIdRoute
  '/_app/students/': typeof AppStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/enquiries'
    | '/exams'
    | '/fees'
    | '/finance'
    | '/guide'
    | '/more'
    | '/papers'
    | '/print'
    | '/routine'
    | '/settings'
    | '/setup'
    | '/students'
    | '/teachers'
    | '/students/$id'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/attendance'
    | '/enquiries'
    | '/exams'
    | '/fees'
    | '/finance'
    | '/guide'
    | '/more'
    | '/papers'
    | '/print'
    | '/routine'
    | '/settings'
    | '/setup'
    | '/teachers'
    | '/'
    | '/students/$id'
    | '/students'
  id:
    | '__root__'
    | '/_app'
    | '/_app/attendance'
    | '/_app/enquiries'
    | '/_app/exams'
    | '/_app/fees'
    | '/_app/finance'
    | '/_app/guide'
    | '/_app/more'
    | '/_app/papers'
    | '/_app/print'
    | '/_app/routine'
    | '/_app/settings'
    | '/_app/setup'
    | '/_app/students'
    | '/_app/teachers'
    | '/_app/'
    | '/_app/students/$id'
    | '/_app/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enquiries': {
      id: '/_app/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AppEnquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams': {
      id: '/_app/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide': {
      id: '/_app/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/papers': {
      id: '/_app/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof AppPapersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print': {
      id: '/_app/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof AppPrintRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routine': {
      id: '/_app/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof AppRoutineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/$id': {
      id: '/_app/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsIdRoute: typeof AppStudentsIdRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsIdRoute: AppStudentsIdRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppEnquiriesRoute: typeof AppEnquiriesRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGuideRoute: typeof AppGuideRoute
  AppMoreRoute: typeof AppMoreRoute
  AppPapersRoute: typeof AppPapersRoute
  AppPrintRoute: typeof AppPrintRoute
  AppRoutineRoute: typeof AppRoutineRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppTeachersRoute: typeof AppTeachersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppEnquiriesRoute: AppEnquiriesRoute,
  AppExamsRoute: AppExamsRoute,
  AppFeesRoute: AppFeesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGuideRoute: AppGuideRoute,
  AppMoreRoute: AppMoreRoute,
  AppPapersRoute: AppPapersRoute,
  AppPrintRoute: AppPrintRoute,
  AppRoutineRoute: AppRoutineRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppTeachersRoute: AppTeachersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
